# Generated by Django 4.1.5 on 2024-06-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_artist_character_game_tags_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='description',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gallery/'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gallery/'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.character'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gallery/'),
        ),
    ]
